apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: flask-redis-app:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        resources:
          limits:
            memory: 128Mi
            cpu: 250m
          requests:
            memory: 64Mi
            cpu: 125m
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 5
        env:
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: flask-config
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: flask-config
              key: REDIS_PORT
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: flask-secret
              key: REDIS_PASSWORD